{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### functon 1 讀取檔案\n",
    "input ： path, is_display(bool)\n",
    "\n",
    "\n",
    "output： 物件"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 199,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from OCC.Display.SimpleGui import init_display\n",
    "from OCC.Extend.DataExchange import read_iges_file\n",
    "\n",
    "def read_file(path, is_display=False):\n",
    "    \n",
    "    if os.path.exists(path):           # 防止路徑不存在\n",
    "        shapes = read_iges_file(path)  # 一定要用這個方法讀取\n",
    "    else:\n",
    "        print(\"檔案路徑錯誤！\")\n",
    "    \n",
    "    if is_display:\n",
    "        # 初始化 3D 顯示環境\n",
    "        display, start_display, add_menu, add_function_to_menu = init_display()\n",
    "        display.DisplayShape(shapes, update=True)\n",
    "        start_display()\n",
    "        \n",
    "    return shapes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 200,
   "metadata": {},
   "outputs": [],
   "source": [
    "path = r\"C:\\NTHU\\IRTI-Project\\simple_1.IGS\" #物件路徑\n",
    "object_1 = read_file(path, is_display=1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### functon 2 分割物件平面\n",
    "input ： object, save_path, is_save(bool)\n",
    "\n",
    "output： 面 1 ~ 面 n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 201,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from OCC.Core.TopExp import TopExp_Explorer\n",
    "from OCC.Core.TopoDS import topods\n",
    "from OCC.Core.TopAbs import TopAbs_FACE\n",
    "from OCC.Display.OCCViewer import OffscreenRenderer\n",
    "\n",
    "# 平面影像儲存路徑\n",
    "image_directory = r\"C:\\NTHU\\IRTI-Project\\Images\"\n",
    "\n",
    "def plane_segmentation(object, save_path, is_save=True):\n",
    "    \n",
    "    if not os.path.exists(save_path):        # 如果 save_path 不存在，則創建一個\n",
    "        os.makedirs(save_path)\n",
    "        \n",
    "    \n",
    "    explorer = TopExp_Explorer(object, TopAbs_FACE) # TopAbs_FACE 只對面感興趣\n",
    "    faces = []\n",
    "    index = 1\n",
    "    # 宣告一個渲彩器(不會顯示出來)\n",
    "    renderer = OffscreenRenderer()\n",
    "    renderer.Create()\n",
    "    \n",
    "    while explorer.More():\n",
    "        \n",
    "        face = topods.Face(explorer.Current())\n",
    "        faces.append(face)                     # 將當前的面儲存到 list 中\n",
    "        \n",
    "        renderer.EraseAll()\n",
    "        renderer.DisplayShape(face, update=True, color='BLUE', transparency=0.5)  # 可以調整顏色和透明度\n",
    "        renderer.FitAll()\n",
    "        \n",
    "        if is_save:\n",
    "            image_path = os.path.join(image_directory, f'object_face_{index}.png')            \n",
    "            renderer.View.Dump(image_path)\n",
    "            print(f'Saved image of face {index} to {image_path}')\n",
    "\n",
    "        index += 1\n",
    "        explorer.Next()                      # 移動到下一個面\n",
    "    \n",
    "    return faces"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 202,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Many colors for color name BLUE, using first.\n",
      "Saved image of face 1 to C:\\NTHU\\IRTI-Project\\Images\\object_face_1.png\n",
      "Many colors for color name BLUE, using first.\n",
      "Saved image of face 2 to C:\\NTHU\\IRTI-Project\\Images\\object_face_2.png\n",
      "Many colors for color name BLUE, using first.\n",
      "Saved image of face 3 to C:\\NTHU\\IRTI-Project\\Images\\object_face_3.png\n",
      "Many colors for color name BLUE, using first.\n",
      "Saved image of face 4 to C:\\NTHU\\IRTI-Project\\Images\\object_face_4.png\n",
      "Many colors for color name BLUE, using first.\n",
      "Saved image of face 5 to C:\\NTHU\\IRTI-Project\\Images\\object_face_5.png\n",
      "Many colors for color name BLUE, using first.\n",
      "Saved image of face 6 to C:\\NTHU\\IRTI-Project\\Images\\object_face_6.png\n",
      "object_1 總共有 6 個物件\n"
     ]
    }
   ],
   "source": [
    "object_1_faces = plane_segmentation(object_1, image_directory)\n",
    "print(\"object_1 總共有\", len(object_1_faces), \"個物件\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### functon 3 平面+線段 生成 drive plane\n",
    "input ： 平面 選擇的邊線 \n",
    "\n",
    "output： 面 1 ~ 面 n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 203,
   "metadata": {},
   "outputs": [],
   "source": [
    "## 讀取所有邊驗的功能\n",
    "from OCC.Core.TopoDS import topods_Edge\n",
    "from OCC.Core.TopAbs import TopAbs_EDGE\n",
    "from OCC.Core.BRepAdaptor import BRepAdaptor_Curve\n",
    "def edges(face):\n",
    "    edge_explorer = TopExp_Explorer(face, TopAbs_EDGE)\n",
    "    edges = []\n",
    "    while edge_explorer.More():\n",
    "        edge = topods_Edge(edge_explorer.Current())\n",
    "        edges.append(edge)\n",
    "        edge_explorer.Next()\n",
    "    return edges[0]\n",
    "\n",
    "# def edges(face):\n",
    "#     edge_explorer = TopExp_Explorer(face, TopAbs_EDGE)\n",
    "#     edges = []\n",
    "#     while edge_explorer.More():\n",
    "        \n",
    "#         edge = topods_Edge(edge_explorer.Current())\n",
    "#         curve_adaptor = BRepAdaptor_Curve(edge)\n",
    "#         if curve_adaptor.GetType() == 0:\n",
    "#             selected_edge = edge\n",
    "#             return selected_edge\n",
    "#         edges.append(edge)\n",
    "#         edge_explorer.Next()\n",
    "    \n",
    "#     return edges[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 204,
   "metadata": {},
   "outputs": [],
   "source": [
    "from OCC.Core.gp import gp_Pnt, gp_Dir, gp_Pln, gp_Vec\n",
    "from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeFace\n",
    "from OCC.Core.BRepAdaptor import BRepAdaptor_Curve\n",
    "from OCC.Core.GCPnts import GCPnts_UniformAbscissa\n",
    "from OCC.Display.SimpleGui import init_display\n",
    "from OCC.Core.BRepAlgoAPI import BRepAlgoAPI_Section\n",
    "from OCC.Core.TopExp import TopExp_Explorer\n",
    "from OCC.Core.TopoDS import topods_Face\n",
    "from OCC.Core.GCPnts import GCPnts_AbscissaPoint\n",
    "from OCC.Core.GCPnts import GCPnts_UniformAbscissa  # 如果使用均匀参数化\n",
    "from OCC.Core.BRepLProp import BRepLProp_SLProps\n",
    "from OCC.Core.BRepAdaptor import BRepAdaptor_Surface\n",
    "from OCC.Core.GeomAPI import GeomAPI_ProjectPointOnSurf\n",
    "from OCC.Core.BRep import BRep_Tool\n",
    "from OCC.Core.TopAbs import TopAbs_FACE"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 205,
   "metadata": {},
   "outputs": [],
   "source": [
    "def calculate_section(face, length, curve_adaptor, name = '', plane_spacing = 10.0, point_spacing = 5.0, is_save=True, is_display=False):\n",
    "    adaptor_surface = BRepAdaptor_Surface(face, True)\n",
    "    props = BRepLProp_SLProps(adaptor_surface, 2, 0.01)\n",
    "    num_planes = int(length / plane_spacing) + 1\n",
    "    path_index = 0\n",
    "    \n",
    "    if length % plane_spacing != 0:\n",
    "        iter_plane = num_planes + 1\n",
    "    else:\n",
    "        iter_plane = num_planes\n",
    "    \n",
    "    for i in range(0, iter_plane):\n",
    "        path_index += 1\n",
    "        u = curve_adaptor.FirstParameter() + i * plane_spacing\n",
    "        if u >= curve_adaptor.LastParameter():\n",
    "            u = curve_adaptor.LastParameter()\n",
    "        pnt = curve_adaptor.Value(u)\n",
    "        tangent_vector = curve_adaptor.DN(u, 1).Normalized()\n",
    "        tangent_dir = gp_Dir(tangent_vector)\n",
    "        \n",
    "        perpendicular_plane = gp_Pln(pnt, tangent_dir)\n",
    "        perpendicular_face = BRepBuilderAPI_MakeFace(perpendicular_plane, -110, 110, -110, 110).Face()\n",
    "        if is_display:\n",
    "            display.DisplayShape(perpendicular_face, update=True, color='RED', transparency=0.5)\n",
    "            \n",
    "        section = BRepAlgoAPI_Section(face, perpendicular_face, False)\n",
    "        section.ComputePCurveOn1(True)\n",
    "        section.Build()\n",
    "        \n",
    "        if section.IsDone():\n",
    "            intersection_shape = section.Shape()\n",
    "            if is_display:\n",
    "                display.DisplayShape(intersection_shape, update=True, color='GREEN')\n",
    "                \n",
    "            explorer = TopExp_Explorer(intersection_shape, TopAbs_EDGE)\n",
    "            edge = topods_Edge(explorer.Current())\n",
    "            curve = BRepAdaptor_Curve(edge)\n",
    "                \n",
    "            curve_length = GCPnts_AbscissaPoint.Length(curve, curve.FirstParameter(), curve.LastParameter())\n",
    "            # curve_length = curve.LastParameter() - curve.FirstParameter()\n",
    "            \n",
    "            num_points = int(curve_length / point_spacing) + 1\n",
    "            \n",
    "            if curve_length % point_spacing != 0:\n",
    "                iter_point = num_points + 1\n",
    "            else:\n",
    "                iter_point = num_points\n",
    "    \n",
    "            for j in range(0, iter_point):\n",
    "                param = curve.FirstParameter() + j * (curve.LastParameter() - curve.FirstParameter()) * point_spacing / curve_length\n",
    "                if param >= curve.LastParameter():\n",
    "                    param = curve.LastParameter()\n",
    "                point = curve.Value(param)\n",
    "                if is_display:\n",
    "                    display.DisplayShape(point, update=True, color='YELLOW')\n",
    "                \n",
    "                surface_handle = BRep_Tool.Surface(face)\n",
    "                projector = GeomAPI_ProjectPointOnSurf(point, surface_handle)\n",
    "                \n",
    "                if projector.NbPoints() > 0:\n",
    "                    u, v = projector.LowerDistanceParameters()\n",
    "                else:\n",
    "                    print(\"No projection found for this point\")\n",
    "                    \n",
    "                props.SetParameters(u, v)\n",
    "                if props.IsCurvatureDefined():\n",
    "                    normal = props.Normal()\n",
    "                if face.Orientation() == TopAbs_FACE:\n",
    "                    normal.Reverse()\n",
    "                if is_save:\n",
    "                    with open(name  + '.txt', 'a') as outfile:\n",
    "                        outfile.write(str(face_index) + '\\t' + str(path_index) +\n",
    "                                    '\\t' + format(point.X(), \".2f\") + '\\t' + format(point.Y(), \".2f\") + '\\t' + format(point.Z(), \".2f\") +\n",
    "                                    '\\t' + format(normal.X(), \".2f\") + '\\t' + format(normal.Y(), \".2f\") + '\\t' + format(normal.Z(), \".2f\") + '\\n')\n",
    "        \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "face_index = 0\n",
    "display, start_display, add_menu, add_function_to_menu = init_display()\n",
    "display.DisplayShape(object_1, update=True)\n",
    "for face in object_1_faces:\n",
    "    face = topods_Face(face)\n",
    "    \n",
    "    face_index += 1\n",
    "    \n",
    "    selected_edge = edges(face) ################\n",
    "    \n",
    "    curve_adaptor = BRepAdaptor_Curve(selected_edge)\n",
    "    length = curve_adaptor.LastParameter() - curve_adaptor.FirstParameter()\n",
    "    \n",
    "    calculate_section(face=face, length=length, curve_adaptor=curve_adaptor, name='simple_1', plane_spacing = 20.0, point_spacing = 20.0, is_save=True, is_display=True)\n",
    "        \n",
    "start_display()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 207,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# face_index = 0\n",
    "# display, start_display, add_menu, add_function_to_menu = init_display()\n",
    "# display.DisplayShape(object_1, update=True)\n",
    "# for face in object_1_faces:\n",
    "#     face = topods_Face(face)\n",
    "#     face_index += 1\n",
    "#     adaptor_surface = BRepAdaptor_Surface(face, True)\n",
    "#     props = BRepLProp_SLProps(adaptor_surface, 2, 0.01)\n",
    "    \n",
    "#     selected_edge = edges(face) ################\n",
    "    \n",
    "#     curve_adaptor = BRepAdaptor_Curve(selected_edge)\n",
    "#     length = curve_adaptor.LastParameter() - curve_adaptor.FirstParameter()\n",
    "    \n",
    "#     num_planes = 5\n",
    "#     spacing = length / (num_planes + 1)    \n",
    "    \n",
    "#     path_index = 0\n",
    "    \n",
    "#     for i in range(1, num_planes + 1):\n",
    "#         path_index += 1\n",
    "#         u = curve_adaptor.FirstParameter() + i * spacing\n",
    "#         pnt = curve_adaptor.Value(u)\n",
    "#         tangent_vector = curve_adaptor.DN(u, 1).Normalized()\n",
    "#         tangent_dir = gp_Dir(tangent_vector)\n",
    "        \n",
    "#         perpendicular_plane = gp_Pln(pnt, tangent_dir)\n",
    "#         perpendicular_face = BRepBuilderAPI_MakeFace(perpendicular_plane, -110, 110, -110, 110).Face()\n",
    "#         display.DisplayShape(perpendicular_face, update=True, color='RED', transparency=0.5)\n",
    "        \n",
    "#         section = BRepAlgoAPI_Section(face, perpendicular_face, False)\n",
    "#         section.ComputePCurveOn1(True)\n",
    "#         section.Build()\n",
    "        \n",
    "#         if section.IsDone():\n",
    "#             intersection_shape = section.Shape()\n",
    "#             display.DisplayShape(intersection_shape, update=True, color='GREEN')\n",
    "            \n",
    "#             explorer = TopExp_Explorer(intersection_shape, TopAbs_EDGE)\n",
    "#             edge = topods_Edge(explorer.Current())\n",
    "#             curve = BRepAdaptor_Curve(edge)\n",
    "            \n",
    "#             num_points = 10\n",
    "#             curve_length = GCPnts_AbscissaPoint.Length(curve, curve.FirstParameter(), curve.LastParameter())\n",
    "#             points = GCPnts_UniformAbscissa(curve, curve_length / num_points, curve.FirstParameter())\n",
    "            \n",
    "#             for j in range(1, num_points + 1):\n",
    "#                 param = points.Parameter(j)\n",
    "#                 point = curve.Value(param)\n",
    "#                 display.DisplayShape(point, update=True, color='YELLOW')\n",
    "                \n",
    "#                 surface_handle = BRep_Tool.Surface(face)\n",
    "#                 projector = GeomAPI_ProjectPointOnSurf(point, surface_handle)\n",
    "                \n",
    "#                 if projector.NbPoints() > 0:\n",
    "#                     u, v = projector.LowerDistanceParameters()\n",
    "#                 else:\n",
    "#                     print(\"No projection found for this point\")\n",
    "                    \n",
    "#                 props.SetParameters(u, v)\n",
    "#                 if props.IsCurvatureDefined():\n",
    "#                     normal = props.Normal()\n",
    "#                 if face.Orientation() == TopAbs_FACE:\n",
    "#                     normal.Reverse()\n",
    "                    \n",
    "#                 with open('simple_1'  + '.txt', 'a') as outfile:\n",
    "#                     outfile.write('\\t' + str(face_index) + '\\t' + str(path_index) +\n",
    "#                                   '\\t' + format(point.X(), \".2f\") + '\\t' + format(point.Y(), \".2f\") + '\\t' + format(point.Z(), \".2f\") +\n",
    "#                                   '\\t' + format(normal.X(), \".2f\") + '\\t' + format(normal.Y(), \".2f\") + '\\t' + format(normal.Z(), \".2f\") + '\\n')\n",
    "        \n",
    "#                 normal_vector = gp_Vec(normal.XYZ())\n",
    "#                 pnt_as_vec = gp_Vec(point.X(), point.Y(), point.Z())\n",
    "#                 start = pnt_as_vec + normal_vector*10\n",
    "#                 pnt_start = gp_Pnt(start.X(), start.Y(), start.Z())\n",
    "        \n",
    "#                 display.DisplayVector(normal_vector, point)\n",
    "# start_display()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pyoccenv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
